version: '3.7'
services:
  ethot:
    image: counterstrafe/ethot
    restart: "no"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'ebotv3'
      MYSQL_USER: 'ebotv3'
      MYSQL_PASS: '${MYSQL_PASS}'
    secrets:
      - secrets.edn

  ebot:
    image: hsfactory/ebot
    restart: always
    ports:
      - "12360:12360"
      - "12361:12361"
      - "12360:12360/udp"
      - "12361:12361/udp"
    volumes:
      - /opt/docker/ebot/logs:/ebot/logs
      - /opt/docker/ebot/demos:/ebot/demos
    environment:
      EXTERNAL_IP: '${EXTERNAL_IP}'
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'ebotv3'
      MYSQL_USER: 'ebotv3'
      MYSQL_PASS: '${MYSQL_PASS}'
      LO3_METHOD: 'restart'
      KO3_METHOD: 'restart'
      DEMO_DOWNLOAD: 'true'
      REMIND_RECORD: 'false'
      DAMAGE_REPORT: 'true'
      DELAY_READY: 'false'
      NODE_STARTUP_METHOD: 'node'
      USE_DELAY_END_RECORD: 'true'
      TOORNAMENT_PLUGIN_KEY: ''

  ebotweb:
    image: counterstrafe/ebotweb
    restart: always
    ports:
      - "80:80"
    volumes:
      - /opt/docker/ebot/demos:/opt/ebot/demos
      - /opt/docker/ebot/logs:/opt/ebot/logs
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'ebotv3'
      MYSQL_USER: 'ebotv3'
      MYSQL_PASS: '${MYSQL_PASS}'
      EBOT_ADMIN_USER: 'admin'
      EBOT_ADMIN_PASS: '${EBOT_ADMIN_PASS}'
      EBOT_ADMIN_MAIL: ''
      DEFAULT_MAX_ROUND: '8'
      DEFAULT_RULES: 'counterstrafe_wingman'
      DEFAULT_OVERTIME_STARTMONEY: '10000'
      DEMO_DOWNLOAD: 'true'
      EBOT_PROTO: 'http://'
      EBOT_IP: '${EBOT_IP}'
      EBOT_PORT: '12360'
      TOORNAMENT_ID: '${TOORNAMENT_ID}'
      TOORNAMENT_SECRET: '${TOORNAMENT_SECRET}'
      TOORNAMENT_API_KEY: '${TOORNAMENT_API_KEY}'
      TOORNAMENT_PLUGIN_KEY: ''

  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - mysql
    volumes:
      - /opt/docker/ebot/mysql:/var/lib/mysql
      - ./ethot-db/ethot.sql:/docker-entrypoint-initdb.d/ethot.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=ebotv3
      - MYSQL_USER=ebotv3
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_ROOT_HOST=%
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"

secrets:
  secrets.edn:
    file: ./secrets.edn

